version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: db-docker-container
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: admin
      POSTGRES_DB: tpccdb
    command: postgres -c config_file=/var/lib/postgresql/data/postgresql.conf
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./postgresql-config/postgresql.conf:/var/lib/postgresql/data/postgresql.conf
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d tpccdb"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  pgdata: 
